server:
  port: 8888

spring:
  application:
    name: config-server-github
  
  cloud:
    config:
      server:
        git:
          uri: https://github.com/nazarchykur/sb-cloud-props.git
          basedir: file:///tmp/sb-cloud-props-config-github-clone
          user: nazarchykur
          password: ${MYGITHUB_TOKEN}
          default-label: main
